added ES4_ pseudo-namespace prefix to all environment variables in the configure script, to avoid confusing external scripts (there was a bug when calling out to the sml script, since it was creating an SMLNJ_HOME variable)
--HG--
branch : com.mozilla.es4.smlnj
extra : convert_revision : 9c9ef19c28b5f90abe19cb065a9412080f53ca17

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -620,14 +620,14 @@ LIBS
 build_alias
 host_alias
 target_alias
-SMLNJ
-MLTON
-DIALECT
-DEBUG
-HEAP_SUFFIX
-SMLNJ_TDP
-MLBUILD
-HEAP2EXEC
+ES4_SMLNJ
+ES4_MLTON
+ES4_SML_DIALECT
+ES4_DEBUG
+ES4_HEAP_SUFFIX
+ES4_SMLNJ_TDP
+ES4_MLBUILD
+ES4_HEAP2EXEC
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1662,52 +1662,52 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-DIALECT=smlnj
-SMLNJ="<<search>>"
-MLTON="<<search>>"
-DEBUG=no
+ES4_SML_DIALECT=smlnj
+ES4_SMLNJ="<<search>>"
+ES4_MLTON="<<search>>"
+ES4_DEBUG=no
 
 
 # Check whether --with-smlnj was given.
 if test "${with_smlnj+set}" = set; then
-  withval=$with_smlnj; SMLNJ="$withval"
+  withval=$with_smlnj; ES4_SMLNJ="$withval"
 fi
 
 
 # Check whether --with-mlton was given.
 if test "${with_mlton+set}" = set; then
-  withval=$with_mlton; MLTON="$withval"
+  withval=$with_mlton; ES4_MLTON="$withval"
 fi
 
 
 # Check whether --with-dialect was given.
 if test "${with_dialect+set}" = set; then
-  withval=$with_dialect; DIALECT="$withval"
+  withval=$with_dialect; ES4_SML_DIALECT="$withval"
 fi
 
 # Check whether --enable-debug was given.
 if test "${enable_debug+set}" = set; then
-  enableval=$enable_debug; DEBUG="$enableval"
+  enableval=$enable_debug; ES4_DEBUG="$enableval"
 fi
 
 
-{ echo "$as_me:$LINENO: using $DIALECT dialect for building releases" >&5
-echo "$as_me: using $DIALECT dialect for building releases" >&6;}
+{ echo "$as_me:$LINENO: using ${ES4_SML_DIALECT} dialect for building releases" >&5
+echo "$as_me: using ${ES4_SML_DIALECT} dialect for building releases" >&6;}
 
 # 1. Find SML/NJ installation information.
-if test "$SMLNJ" = "yes" -o "$SMLNJ" = "<<search>>"; then
+if test "${ES4_SMLNJ}" = "yes" -o "${ES4_SMLNJ}" = "<<search>>"; then
     for ac_prog in sml
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_SMLNJ+set}" = set; then
+if test "${ac_cv_path_ES4_SMLNJ+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $SMLNJ in
+  case $ES4_SMLNJ in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_SMLNJ="$SMLNJ" # Let the user override the test with a path.
+  ac_cv_path_ES4_SMLNJ="$ES4_SMLNJ" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -1717,7 +1717,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_SMLNJ="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_ES4_SMLNJ="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -1728,107 +1728,107 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-SMLNJ=$ac_cv_path_SMLNJ
-if test -n "$SMLNJ"; then
-  { echo "$as_me:$LINENO: result: $SMLNJ" >&5
-echo "${ECHO_T}$SMLNJ" >&6; }
+ES4_SMLNJ=$ac_cv_path_ES4_SMLNJ
+if test -n "$ES4_SMLNJ"; then
+  { echo "$as_me:$LINENO: result: $ES4_SMLNJ" >&5
+echo "${ECHO_T}$ES4_SMLNJ" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$SMLNJ" && break
+  test -n "$ES4_SMLNJ" && break
 done
 
 fi
 
-if test -n "$SMLNJ" -a -x "$SMLNJ"; then
-    SMLNJ_HOME=`dirname $SMLNJ`
-    MLBUILD="$SMLNJ_HOME"/ml-build
-    HEAP2EXEC="$SMLNJ_HOME"/heap2exec
+if test -n "${ES4_SMLNJ}" -a -x "${ES4_SMLNJ}"; then
+    ES4_SMLNJ_HOME=`dirname ${ES4_SMLNJ}`
+    ES4_MLBUILD="${ES4_SMLNJ_HOME}"/ml-build
+    ES4_HEAP2EXEC="${ES4_SMLNJ_HOME}"/heap2exec
     { echo "$as_me:$LINENO: checking platform-specific heapfile suffix" >&5
 echo $ECHO_N "checking platform-specific heapfile suffix... $ECHO_C" >&6; }
-    HEAP_SUFFIX=`echo -e 'TextIO.output (TextIO.stdErr, SMLofNJ.SysInfo.getHeapSuffix());' | (${SMLNJ} >/dev/null) 2>&1`
-    { echo "$as_me:$LINENO: result: $HEAP_SUFFIX" >&5
-echo "${ECHO_T}$HEAP_SUFFIX" >&6; }
+    ES4_HEAP_SUFFIX=`echo -e 'TextIO.output (TextIO.stdErr, SMLofNJ.SysInfo.getHeapSuffix());' | (${ES4_SMLNJ} >/dev/null) 2>&1`
+    { echo "$as_me:$LINENO: result: ${ES4_HEAP_SUFFIX}" >&5
+echo "${ECHO_T}${ES4_HEAP_SUFFIX}" >&6; }
 else
-    SMLNJ=false
-    SMLNJ_HOME=XXX
-    MLBUILD=false
-    HEAP2EXEC=false
-    HEAP_SUFFIX=XXX
+    ES4_SMLNJ=false
+    ES4_SMLNJ_HOME=XXX
+    ES4_MLBUILD=false
+    ES4_HEAP2EXEC=false
+    ES4_HEAP_SUFFIX=XXX
 fi
 
 # 2. SML/NJ dialect
 
-if test "$DIALECT" = "smlnj"; then
-    if test "$SMLNJ" = "false"; then
+if test "${ES4_SML_DIALECT}" = "smlnj"; then
+    if test "${ES4_SMLNJ}" = "false"; then
         { { echo "$as_me:$LINENO: error: cannot execute sml" >&5
 echo "$as_me: error: cannot execute sml" >&2;}
    { (exit 1); exit 1; }; }
     fi
     { echo "$as_me:$LINENO: checking whether ml-build is executable" >&5
 echo $ECHO_N "checking whether ml-build is executable... $ECHO_C" >&6; }
-if test -x "$MLBUILD"; then
+if test -x "${ES4_MLBUILD}"; then
     { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 else
     { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-    { { echo "$as_me:$LINENO: error: cannot execute $MLBUILD" >&5
-echo "$as_me: error: cannot execute $MLBUILD" >&2;}
+    { { echo "$as_me:$LINENO: error: cannot execute ${ES4_MLBUILD}" >&5
+echo "$as_me: error: cannot execute ${ES4_MLBUILD}" >&2;}
    { (exit 1); exit 1; }; }
 fi
     { echo "$as_me:$LINENO: checking usability of heap2exec on this platform" >&5
 echo $ECHO_N "checking usability of heap2exec on this platform... $ECHO_C" >&6; }
-    if test -x "$HEAP2EXEC"; then
-        echo -e 'SMLofNJ.exportFn("autoconf-test.heap",(fn _ => OS.Process.success));' | (sml >/dev/null) 2>&1
-        "$HEAP2EXEC" autoconf-test.heap.${HEAP_SUFFIX} autoconf-test >/dev/null 2>&1
+    if test -x "${ES4_HEAP2EXEC}"; then
+        echo -e 'SMLofNJ.exportFn("autoconf-test.heap",(fn _ => OS.Process.success));' | (${ES4_SMLNJ} >/dev/null) 2>&1
+        "${ES4_HEAP2EXEC}" autoconf-test.heap.${ES4_HEAP_SUFFIX} autoconf-test >/dev/null 2>&1
         if test "$?" = "0"; then
             { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
         else
             { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-            HEAP2EXEC=false
+            ES4_HEAP2EXEC=false
         fi
     else
         { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-        HEAP2EXEC=false
+        ES4_HEAP2EXEC=false
     fi
-    rm -f autoconf-test.heap.${HEAP_SUFFIX}
+    rm -f autoconf-test.heap.${ES4_HEAP_SUFFIX}
     rm -f autoconf-test
 
     { echo "$as_me:$LINENO: checking availability of smlnj-tdp tools" >&5
 echo $ECHO_N "checking availability of smlnj-tdp tools... $ECHO_C" >&6; }
-    SMLNJ_TDP=`echo -e 'TextIO.output (TextIO.stdErr, valOf(case (CM.Anchor.anchor "smlnj-tdp") of { get, ... } => get ()));' | (${SMLNJ} >/dev/null) 2>&1`
-    if test -z "$SMLNJ_TDP"; then
+    ES4_SMLNJ_TDP=`echo -e 'TextIO.output (TextIO.stdErr, valOf(case (CM.Anchor.anchor "smlnj-tdp") of { get, ... } => get ()));' | (${ES4_SMLNJ} >/dev/null) 2>&1`
+    if test -z "${ES4_SMLNJ_TDP}"; then
         { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
     else
-        { echo "$as_me:$LINENO: result: $SMLNJ_TDP" >&5
-echo "${ECHO_T}$SMLNJ_TDP" >&6; }
+        { echo "$as_me:$LINENO: result: ${ES4_SMLNJ_TDP}" >&5
+echo "${ECHO_T}${ES4_SMLNJ_TDP}" >&6; }
     fi
 fi
 
 # 3. MLton dialect
 
-if test "$DIALECT" = "mlton"; then
-    if test "$MLTON" = "yes" -o "$MLTON" = "<<search>>"; then
+if test "${ES4_SML_DIALECT}" = "mlton"; then
+    if test "${ES4_MLTON}" = "yes" -o "${ES4_MLTON}" = "<<search>>"; then
         for ac_prog in mlton
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
-if test "${ac_cv_path_MLTON+set}" = set; then
+if test "${ac_cv_path_ES4_MLTON+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $MLTON in
+  case $ES4_MLTON in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_MLTON="$MLTON" # Let the user override the test with a path.
+  ac_cv_path_ES4_MLTON="$ES4_MLTON" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -1838,7 +1838,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
-    ac_cv_path_MLTON="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_ES4_MLTON="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -1849,20 +1849,20 @@ IFS=$as_save_IFS
   ;;
 esac
 fi
-MLTON=$ac_cv_path_MLTON
-if test -n "$MLTON"; then
-  { echo "$as_me:$LINENO: result: $MLTON" >&5
-echo "${ECHO_T}$MLTON" >&6; }
+ES4_MLTON=$ac_cv_path_ES4_MLTON
+if test -n "$ES4_MLTON"; then
+  { echo "$as_me:$LINENO: result: $ES4_MLTON" >&5
+echo "${ECHO_T}$ES4_MLTON" >&6; }
 else
   { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 
-  test -n "$MLTON" && break
+  test -n "$ES4_MLTON" && break
 done
 
-        if test -z "$MLTON"; then
+        if test -z "${ES4_MLTON}"; then
             { { echo "$as_me:$LINENO: error: cannot find installation of MLton" >&5
 echo "$as_me: error: cannot find installation of MLton" >&2;}
    { (exit 1); exit 1; }; }
@@ -1870,18 +1870,18 @@ echo "$as_me: error: cannot find installation of MLton" >&2;}
     fi
     { echo "$as_me:$LINENO: checking whether mlton is executable" >&5
 echo $ECHO_N "checking whether mlton is executable... $ECHO_C" >&6; }
-if test -x "$MLTON"; then
+if test -x "${ES4_MLTON}"; then
     { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 else
     { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-    { { echo "$as_me:$LINENO: error: cannot execute $MLTON" >&5
-echo "$as_me: error: cannot execute $MLTON" >&2;}
+    { { echo "$as_me:$LINENO: error: cannot execute ${ES4_MLTON}" >&5
+echo "$as_me: error: cannot execute ${ES4_MLTON}" >&2;}
    { (exit 1); exit 1; }; }
 fi
 else
-    MLTON=false
+    ES4_MLTON=false
 fi
 
 
@@ -2562,14 +2562,14 @@ LIBS!$LIBS$ac_delim
 build_alias!$build_alias$ac_delim
 host_alias!$host_alias$ac_delim
 target_alias!$target_alias$ac_delim
-SMLNJ!$SMLNJ$ac_delim
-MLTON!$MLTON$ac_delim
-DIALECT!$DIALECT$ac_delim
-DEBUG!$DEBUG$ac_delim
-HEAP_SUFFIX!$HEAP_SUFFIX$ac_delim
-SMLNJ_TDP!$SMLNJ_TDP$ac_delim
-MLBUILD!$MLBUILD$ac_delim
-HEAP2EXEC!$HEAP2EXEC$ac_delim
+ES4_SMLNJ!$ES4_SMLNJ$ac_delim
+ES4_MLTON!$ES4_MLTON$ac_delim
+ES4_SML_DIALECT!$ES4_SML_DIALECT$ac_delim
+ES4_DEBUG!$ES4_DEBUG$ac_delim
+ES4_HEAP_SUFFIX!$ES4_HEAP_SUFFIX$ac_delim
+ES4_SMLNJ_TDP!$ES4_SMLNJ_TDP$ac_delim
+ES4_MLBUILD!$ES4_MLBUILD$ac_delim
+ES4_HEAP2EXEC!$ES4_HEAP2EXEC$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
